import { Project } from "@/types";

export const projects: Project[] = [
  {
    id: "stock-market",
    title: "Stock Market App",
    slug: "stock-market",
    description: "Real-time stock tracking with AI-powered predictions and portfolio management.",
    longDescription:
      "A comprehensive stock market application that provides real-time price tracking, AI-powered predictions, and portfolio management tools. Built with modern web technologies and integrated with financial data APIs for accurate, up-to-date market information.",
    techStack: ["React", "Next.js", "TypeScript", "Python", "TailwindCSS", "AI/ML"],
    features: [
      "Real-time stock price tracking",
      "AI-powered price predictions",
      "Portfolio management dashboard",
      "Market trend analysis",
      "Watchlist functionality",
    ],
    githubUrl: "https://github.com/devfromnyc/stock-market-app",
    liveUrl: "https://stock-market-app-beta-eight.vercel.app",
    screenshots: ["/images/projects/stock-market-1.png"],
    icon: "folder-chart",
    featured: true,
  },
  {
    id: "family-meal-planner",
    title: "Family Meal Planner",
    slug: "family-meal-planner",
    description: "AI-powered meal planning for families with smart grocery list generation.",
    longDescription:
      "A shared household meal planner that uses Gemini AI to draft toddler-friendly meals based on family preferences. Features weekly planning, recipe library, ratings system, and automatic grocery list aggregation.",
    techStack: ["Next.js", "React", "TypeScript", "TailwindCSS", "PostgreSQL", "Gemini AI"],
    features: [
      "AI-generated meal suggestions",
      "Weekly meal planning grid",
      "Recipe library with favorites",
      "Smart grocery list aggregation",
      "Family preference settings",
    ],
    githubUrl: "https://github.com/devfromnyc/family-meal-planner",
    liveUrl: "https://family-meal-planner-hazel-beta.vercel.app",
    screenshots: ["/images/projects/meal-planner-1.png"],
    icon: "folder-star",
    featured: true,
  },
  {
    id: "bucket-list",
    title: "Bucket List",
    slug: "bucket-list",
    description: "Goal tracking application to manage and achieve your life aspirations.",
    longDescription:
      "A beautiful goal tracking application that helps users organize, plan, and achieve their bucket list items. Features progress tracking, category organization, and milestone celebrations.",
    techStack: ["React", "Next.js", "TypeScript", "TailwindCSS", "MongoDB"],
    features: [
      "Goal categorization",
      "Progress tracking",
      "Milestone celebrations",
      "Photo memories",
      "Sharing capabilities",
    ],
    githubUrl: "https://github.com/devfromnyc/bucket-list",
    liveUrl: "https://bucket-list-delta.vercel.app",
    screenshots: ["/images/projects/bucket-list-1.png"],
    icon: "folder-star",
    featured: true,
  },
  {
    id: "breathwork-guru",
    title: "Breathwork Guru",
    slug: "breathwork-guru",
    description: "Wellness business site helping clients overcome alcohol addiction through breathwork.",
    longDescription:
      "A modern business website built for a wellness professional specializing in breathwork techniques for alcohol addiction recovery. Features a clean, calming design with information about services, booking capabilities, and resources for clients.",
    techStack: ["React 19", "Vite", "React Router", "TailwindCSS"],
    features: [
      "Responsive modern design",
      "Service information pages",
      "Client resources",
      "Contact integration",
    ],
    githubUrl: "https://github.com/devfromnyc/client-site-1",
    liveUrl: "https://client-site-1-psi.vercel.app/",
    screenshots: ["/images/projects/breathwork-1.png"],
    icon: "folder-star",
    featured: false,
  },
  {
    id: "ecommerce-fullstack",
    title: "Fullstack E-commerce Store",
    slug: "ecommerce-fullstack",
    description: "Complete e-commerce platform with authentication, database, and shopping cart.",
    longDescription:
      "A fully functional e-commerce store built from the ground up with Next.js 16 and React 19. Features user authentication, PostgreSQL database with Drizzle ORM, product catalog, shopping cart with Zustand state management, and a clean modern UI.",
    techStack: ["Next.js 16", "React 19", "TypeScript", "Drizzle ORM", "Neon PostgreSQL", "Zustand", "TailwindCSS"],
    features: [
      "User authentication with Better Auth",
      "PostgreSQL database with Drizzle ORM",
      "Shopping cart functionality",
      "Product catalog with filtering",
      "Responsive modern design",
    ],
    githubUrl: "https://github.com/devfromnyc/ecommerce-fullstack-store",
    liveUrl: "https://ecommerce-fullstack-store.vercel.app/",
    screenshots: ["/images/projects/ecommerce-fullstack-1.png"],
    icon: "folder-code",
    featured: true,
  },
  {
    id: "live-conscious",
    title: "Live Conscious",
    slug: "live-conscious",
    description: "Production Shopify storefront I contribute to in my current role.",
    longDescription:
      "Live Conscious is a Shopify store for a wellness brand that sells collagen peptides, greens, and other daily supplements. The site merchandises bestsellers and a subscribe-and-save program around hair, skin, nails, and joint support, with a 365-day money-back guarantee.",
    techStack: ["Shopify", "Liquid", "JavaScript", "CSS"],
    features: [
      "Ongoing production storefront work",
      "Shopify theme and checkout customizations",
      "Subscription and merchandising features",
    ],
    liveUrl: "https://weliveconscious.com/",
    screenshots: ["/images/projects/live-conscious-1.png"],
    icon: "folder",
    featured: false,
    origin: "production",
  },
  {
    id: "essential-elements",
    title: "Essential Elements",
    slug: "essential-elements",
    description: "Production Shopify storefront I contribute to in my current role.",
    longDescription:
      "Essential Elements is a Shopify store for science-backed health and wellness supplements, including T-support, apple cider vinegar gummies, and hydration products. The storefront uses a no-fluff brand voice and a catalog aimed at everyday fitness and wellness goals.",
    techStack: ["Shopify", "Liquid", "JavaScript", "CSS"],
    features: [
      "Ongoing production storefront work",
      "Shopify theme and checkout customizations",
      "Product catalog and conversion work",
    ],
    liveUrl: "https://essentialelementsnutrition.com/",
    screenshots: ["/images/projects/essential-elements-1.png"],
    icon: "folder",
    featured: false,
    origin: "production",
  },
  {
    id: "tru-alchemy",
    title: "Tru Alchemy",
    slug: "tru-alchemy",
    description: "Production Shopify storefront I contribute to in my current role.",
    longDescription:
      "Tru Alchemy is a Shopify store for clean, holistic skincare sold as a self-care ritual. The catalog highlights formulas with activated vitamin C, patented Hyaluronix moisture technology, a proprietary acid blend, bakuchiol, and other nature-meets-science ingredients.",
    techStack: ["Shopify", "Liquid", "JavaScript", "CSS"],
    features: [
      "Ongoing production storefront work",
      "Shopify theme and checkout customizations",
      "Product and content page work",
    ],
    liveUrl: "https://trualchemyskin.com/",
    screenshots: ["/images/projects/tru-alchemy-1.png"],
    icon: "folder",
    featured: false,
    origin: "production",
  },
  {
    id: "1md-nutrition",
    title: "1MD Nutrition",
    slug: "1md-nutrition",
    description: "Production Shopify storefront I contribute to in my current role.",
    longDescription:
      "1MD Nutrition is a Shopify store for physician-formulated supplements with clinically studied ingredients. The site sells products across liver, vision, bone, digestive, and other health categories, and pairs the catalog with doctor-led education and health guides.",
    techStack: ["Shopify", "Liquid", "JavaScript", "CSS"],
    features: [
      "Ongoing production storefront work",
      "Shopify theme and checkout customizations",
      "High-traffic ecommerce production work",
    ],
    liveUrl: "https://1md.org/",
    screenshots: ["/images/projects/1md-1.png"],
    icon: "folder",
    featured: false,
    origin: "production",
  },
];

export const featuredProjects = projects.filter((p) => p.featured);
